server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

spring:
  profiles:
    include: db, file
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:

#file:
#  profileImg: ProfileImg/
#  boardImg: BoardImg/
#  itineraryImg: ItineraryImg/

iam:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

env: server
logTracer: false

jwt:
  header: Authorization
##HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400